---
matrix:
  include:
  - IMAGE: debian
    VERSION: latest
  - IMAGE: deluge
    VERSION: 2.1.1-r5
    ARGS: '[ "DELUGE_VERSION=2.1.1-r5", "ANOTHER=TEST" ]'

pipeline:
  build:
    image: plugins/kaniko:1.6
    settings:
      repo: nold360/${IMAGE}
      dockerfile: ${IMAGE}/Containerfile
      build_args: ${ARGS}
      context: ${IMAGE}
      tags:
        - latest
        - ${VERSION}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  scan:
    image: "aquasec/trivy:latest"
    commands:
      - >
        trivy image --no-progress --list-all-pkgs lib42/${IMAGE}:${VERSION}

#-o /cache/trivy-%s.html --format template --template '@/contrib/html.tpl'
