---
matrix:
  include:
  - IMAGE: deluge
    VERSION: 1.2.2

pipeline:
  build:
    image: plugins/kaniko:1.6
    settings:
      repo: nold360/${IMAGE}
      dockerfile: ${IMAGE}/Containerfile
      context: ${IMAGE}
      tags:
        - latest
        - ${VERSION}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
