---
matrix:
  include:
  - IMAGE: base
    VERSION: "bookworm-slim"
    TAG: "latest"
  - IMAGE: deluge
    # renovate: datasource=pip depName=deluge
    VERSION: 2.1.1
    TAG: "latest"
  - IMAGE: conreq
    VERSION: "latest"
    TAG: "latest"
  - IMAGE: squid
    VERSION: "latest"
    TAG: "latest"
  - IMAGE: jackett
    # renovate: datasource=github-releases depName=Jackett/Jackett versioning=loose
    VERSION: 0.20.3486
    TAG: "latest"

when:
  path:
    include:
      - .woodpecker/*
      - containers/${IMAGE}/**
        #branch: main
  event: [ cron, manual, push, tag ]

pipeline:
  build:
    image: reg.dc/buildah
    commands:
      - buildah bud --pull -t "lib42/${IMAGE}:${VERSION}" -t "lib42/${IMAGE}:latest" --build-arg "VERSION=${VERSION}" -f containers/${IMAGE}/Containerfile containers/${IMAGE}
        #      - buildah push  --creds "$${DOCKER_USERNAME}:$${DOCKER_PASSWORD}" "lib42/${IMAGE}:${VERSION}"
      # custom_labels:
      #   - org.opencontainers.image.url=${CI_REPO_LINK}
      #   - org.opencontainers.image.revision=${CI_COMMIT_SHA}
      #   - org.opencontainers.image.vendor=lib42
      #   - org.opencontainers.image.created=${CI_PIPELINE_CREATED}
      # context: containers/${IMAGE}
    secrets:
      - docker_username
      - docker_password
