---
matrix:
  include:
  - IMAGE: deluge
    TAGS: '[ "2.1.1-r6", "latest" ]'
    ARGS: '[ "DELUGE_VERSION=2.1.1-r6" ]'
  - IMAGE: conreq
    TAGS: '[ "latest" ]'
    ARGS: '[]'


pipeline:
  build:
    image: plugins/kaniko:1.6
    settings:
      repo: lib42/${IMAGE}
      dockerfile: ${IMAGE}/Containerfile
      build_args: ${ARGS}
      context: ${IMAGE}
      tags: ${TAGS}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  scan:
    image: "aquasec/trivy:latest"
    commands:
      - >
        trivy image --no-progress --list-all-pkgs lib42/${IMAGE}:${VERSION}

#-o /cache/trivy-%s.html --format template --template '@/contrib/html.tpl'
